### ISSUE TITLE
"Download Image" resizes and adds transparent data

### ISSUE THREAD

**Issue by BryanStuurman** [foxglove/studio#1487]
I'm working with camera and depth image streams for input into an AI, and I've started using foxglove studio to preview bag files recorded "offline" and snip out samples to be fed manually into our AI.
I'd like to be able to save a PNG of precisely the data from the bag file. Currently the images that are saved include a large transparency area boxing (a potentially) resized image from the bag file. It seems like I could manage this a little by tweaking my layout until the panel matches the expected image size, but that doesn't strike me as the most efficient workflow.

Or have a missed a feature already built into FGS?

attached is a sample image where I have managed to get the size correct (640x480) but there is a substantial transparent border (
![camera_aligned_depth_to_color_image_raw-1626287154-711943150](https://user-images.githubusercontent.com/87621617/126083660-a0c20c77-704c-47af-8553-07ce0d089026.png)

**Comment by defunctzombie** [comment]
This is likely a regression I introduced in https://github.com/foxglove/studio/pull/1367. As of that PR the render canvas size is managed separately from the image size so we can render crisp markers. We'll need to fix the download image feature to download only the image data rather than the entire screen render canvas as it does now; thus leading to lots of transparent area around your actual image.
