### ISSUE TITLE
Duplicated Welcome layout on first launch

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#1545]
When the app is first launched the user ends up with two "Welcome" layouts in their list. This looks sloppy and is a bit confusing for users as to why they have two welcome layouts.

**Comment by defunctzombie** [comment]
This issue happens because [openWelcomeLayout](https://github.com/foxglove/studio/blob/main/packages/studio-base/src/Workspace.tsx#L204) is called on first run (when we haven't shown the user a layout). But it seems that a welcome layout has already been setup for the user elsewhere. Haven't found that yet but wanted to update the ticket with this learning.

**Comment by defunctzombie** [comment]
@jtbandes sending your way - I'm working on publish support in extensions
