### ISSUE TITLE
Surface URDF loading error to user

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#1555]
**Description**
This error shows up in our sentry logs. We should handle this error and display a message to the user rather than sending to sentry.

```
Error: Failed to load x-foxglove-ros-package:...  Loading assets from ROS packages requires the ROS_PACKAGE_PATH environment var...
```

https://sentry.io/organizations/foxglove/issues/2528807756/

**Comment by jtbandes** [comment]
Closing since I'm unable to reproduce the issue, and it only seemed to happen to 1 user.

I can reproduce the exception, but it's not an _uncaught_ exception. It propagates up from here:

https://github.com/foxglove/studio/blob/97e55e772a4e2e3a12685d66bdda73bdae2f3ddf/packages/studio-base/src/services/URDFAssetLoader.ts#L94

And is caught and displayed to the user here:

https://github.com/foxglove/studio/blob/97e55e772a4e2e3a12685d66bdda73bdae2f3ddf/packages/studio-base/src/Workspace.tsx#L321
