### ISSUE TITLE
Plot panel slows down when displaying too much data

### ISSUE THREAD

**Issue by sink0918** [foxglove/studio#1641]
**Description**
As I add a data into the plot, the plot starts drawing slower and slower, eventually can't work at all.

- Version:  v0.15.0
- OS: Studio in Windows 11 with ROS noetic in WSL 2 

**Steps To Reproduce**

Connect to ROS 1 Rosbridge then add anything to the plot

**Expected Behavior**
When I using plot in the webviz

https://user-images.githubusercontent.com/57067221/129442644-4bc0ee48-ba4e-4446-902d-9c51b86e4eff.mp4

**Actual Behavior**
When I using plot in the Studio

https://user-images.githubusercontent.com/57067221/129443380-3cdbd3af-c1d4-4502-8dfe-72fc2126c9a7.mp4

**Comment by defunctzombie** [comment]
@sink0918 Thanks for reporting this! We'll take a look.

**Comment by sink0918** [comment]
The problem still exists on v0.15.0 when I turn "X range in seconds" to 5 in the plot panel.

https://user-images.githubusercontent.com/57067221/130574423-095125bb-9a18-41e8-9c14-eeb8f735b1ac.mp4

**Comment by defunctzombie** [comment]
@sink0918 Whats the frequency of `/vision/finally_data.energy_sin_vel` ? How big is the `/vision/finally_data` message itself (i.e. what are the other fields).

**Comment by sink0918** [comment]
> @sink0918 Whats the frequency of `/vision/finally_data.energy_sin_vel` ? How big is the `/vision/finally_data` message itself (i.e. what are the other fields).

In the Studio setting, I turn message_rate to 60 Hz 
![image](https://user-images.githubusercontent.com/57067221/130638698-9e0ec18a-d702-4ec4-be8a-68a4cfcf7a84.png)

And this is the info of `/vision/finally_data` 
![image](https://user-images.githubusercontent.com/57067221/130638982-7dc7daf6-b198-4ae8-b941-f862c7b3cc15.png)

BTW, when I use webviz, all the data added to the plot can be fluently drawn in the exact same settings.

**Comment by defunctzombie** [comment]
@sink0918 Do you mind sharing the message definition for `vision/Data`? I'd like replicate sending a similar message type at 100hz locally. I did similar tests with my own messages (thats how I landed on the referenced fix) but maybe there is more to it based on the message.

If you prefer to share the message definition in private you can do so directly to me via our slack or email.

**Comment by sink0918** [comment]
> @sink0918 Do you mind sharing the message definition for `vision/Data`? I'd like replicate sending a similar message type at 100hz locally. I did similar tests with my own messages (thats how I landed on the referenced fix) but maybe there is more to it based on the message.
> 
> If you prefer to share the message definition in private you can do so directly to me via our slack or email.

I have send the email to contact@foxglove.dev, please check.

**Comment by defunctzombie** [comment]
@sink0918 I looked into the slowdown issue while connected to a live stream. The slowdown comes from the underlying charting library (chartjs) we are using for the plot.

The library has two areas which contribute to the slowdown as more and more data is plotted in realtime. One of these is the rendering of the points. Each point is individually rendered and, as the number of points increases on the plot, the time to render the points increases. This issue also impacts webviz; it just takes a little longer than in studio due to the next issue area which is a change in plugin notification handling in chartjs. Webviz uses chartjs v2.9. In studio, we've upgraded to chartjs v3. From my profiling of studio, chartjs v3 shows a new slowdown in an internal codepath which delivers notifications to plugins. We use two plugins for our plots (datalabels and zoom). While we could look at removing these or finding alternatives it isn't quick and not necessarily likely to fix the underlying chartjs notification slowdown.

These two issues: point rendering and plugin notifications are what contribute to the slowdown as more and more data changes on the streaming chart. We can alleviate the point rendering issue by making point rendering a plot option. This will delay when you start to see rendering latency but also impacts features like hovering to see point data.

Unfortunately there is no quick win here like there was with disabling chart animations which were a contributor to the slowdown issue that impacted the sliding window view. For now I recommend using a window size that provides the streaming experience you are comfortable with. I will keep this issue open and this comment will provide further performance guidance when we are able to spend time looking into this.

**Comment by sink0918** [comment]
Yes, I think the point rendering option may help. Like the `rqt_plot` also have a similar option.

![image](https://user-images.githubusercontent.com/57067221/131223005-731fcff7-3a10-45b4-b30d-e9efe94c2509.png)

**Comment by jessicaaustin** [comment]
FWIW, I've seen similar performance issues with "lots" of plots in a single layout using the default settings of 60Hz for the refresh rate (The `Message Rate` Studio setting). Lowering the refresh rate fixes the problem so far, and that's fine for me because I don't need 60Hz update rate for my use case.

An example of what I mean by "a lot":

![Selection_736](https://user-images.githubusercontent.com/1159930/135360417-ffd9e8a5-b4b6-4af7-a747-afefc96adf89.png)

All the plots here are from topics updating at 20Hz, with a 10s rolling window, and I'm connected directly to the ROS graph. If I use 60Hz then some of the plots will "stick" and fail to update for a few seconds before catching up. At 5Hz everything works fine for 10s-30s windows.

If/when this gets picked up again, happy to test or provide feedback.

**Comment by amacneil** [comment]
@defunctzombie suggested closing out this bug since we addressed the main issues, and open a new feature to allow toggling point rendering which improves performance.

Longer term we have discussed moving to webGL plots for better performance.
