### ISSUE TITLE
Document 3D Panel's lack of transform interpolation

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#1817]
Until we fix https://github.com/foxglove/studio/issues/1846, we should document the current behavior of the 3d panel.

> Should warn users that accuracy of visualization will be impacted, and link to more information about the warning in the documentation.
> - Will need design support re: where warning will be displayed (cc: @2metres)
> - Will need to add documentation to foxglove.dev/docs for impacted users to reference (@esthersweon)

**Comment by defunctzombie** [comment]
https://github.com/foxglove/studio/pull/1813 displays errors when markers are not published in the root frame, but this is undesired behavior since for some robots (jointed) markers may rarely be published in the root frame.

What the app is trying to convey for markers that are not published in the root frame is that there may be inaccuracies with display. Maybe the /tf messages between the two frames are delayed or maybe we need to perform interpolation (which itself is a guess) at where to display the marker relative to the current root frame.

Currently studio does not perform TF interpolation.
