### ISSUE TITLE
Store and load current connection in URL

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1868]
I should be able to bookmark the current page with a websocket connection, and come back to it later.

- When rosbridge connection is used, add this to the URL like `studio.foxglove.dev/?source=rosbridge&conn=wsblahblah`
- Loading this URL should load the rosbridge player
- https://github.com/foxglove/studio/pull/1919/files#r719059578

**Comment by defunctzombie** [comment]
The user-story here is a desire to open the web version of studio with a specific player and parameters. This won't work for all players. We need to be careful about how we introduce/surface some of these concepts and trying to url/browser specific things deep within the app. This was something that I had to extract from PlayerManager and I'd like to avoid us putting it back in the same way since we have web and desktop.

This is also related to our data platform player and `foxglove://` url handling for desktop.

**Comment by amacneil** [comment]
Good point - might be worth separating "layout in the url" from "connection details in the URL".

- Layout makes sense for shared layouts, and personal synced layouts, but unclear how we want to handle localstorage layouts? Maybe it is ok if you save a personal or localstorage layout URL and that URL only works on your computer, since other people don't have access to it?
- Connection details
  - Fairly straight forward for remote connections (ros1+2, rosbridge, http bag, foxglove DP)
  - Maybe also ok for file based connections? We can just have an encoded file path in the URL? Still nice that I can bookmark something and come back to it.

There is a separate discussion about how we can make these URLs "shareable" within the desktop build of Studio (Linear is a good example of prior art, Slack also has some "copy link" options although at per-message level rather than app level).

**Comment by defunctzombie** [comment]
Related: https://github.com/foxglove/studio/issues/1848

**Comment by defunctzombie** [comment]
Re-assigned to @miles who's actively working on this in https://github.com/foxglove/studio/pull/2171

**Comment by miles** [comment]
How is it my username being used on this project? I keep getting notifications on it.

**Comment by foxymiles** [comment]
@miles I think @defunctzombie meant to tag me, @foxymiles .

**Comment by defunctzombie** [comment]
@miles Yea - sorry about that - the username autocomplete led me astray.
