### ISSUE TITLE
Detect expired sessions and signed out

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#1952]
**Description**
When a user signs out in another tab, the original tab spews 401 toasts:

![image](https://user-images.githubusercontent.com/637671/136471415-1b2ad1af-1629-4e83-8ed3-2dd6a498917f.png)

We should intelligently handle sign out across all tabs, no toast necessary.

**Comment by foxymiles** [comment]
@amacneil So the correct thing to do here would be to interpret any 401 response as an invalid session and log out right?

**Comment by amacneil** [comment]
I think so. As long as it wouldn't lead to signing out users during an intermittent server issue.

Maybe there is a more active way we can alert other tabs/windows to the signout action? @defunctzombie for thoughts.

**Comment by defunctzombie** [comment]
Yea - I think detecting 401 would be correct. We just need to make sure that on the console apis we only return 401 when the authorization header is missing or invalid rather than sending 401 for other access failures.

The other option would be to poll the localstorage `fox.signedin` and if it is no longer present then the session is signed out. But that doesn't work well when the server has killed the session so the 401 detection approach is still needed.
