### ISSUE TITLE
Console player: Split memory cache by topic to avoid discarding existing data when subscriptions change

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#1961]

**Comment by defunctzombie** [comment]
@jtbandes I think this might be specific to the current data platform player and not the new iterable player. The iterable player keeps only the messages a user wanted to preload in blocks and when loading new blocks only fetches the topics missing from the block. It does still evict whole blocks but that is by design since that's when we've determined we no longer have enough space to hold the data in memory.
