### ISSUE TITLE
Extensions API: add ability to read and write parameters

### ISSUE THREAD

**Issue by jessicaaustin** [foxglove/studio#1988]
The current Extensions API does not provide access to parameters: you cannot read parameters, or set or delete parameters. This capability is available via roslibjs and is used for the Parameters Panel in Studio. 

At least for our use case, reading parameters is much higher priority than updating or deleting them.

**Comment by jtbandes** [comment]
Should this issue stay open since it was about both reading & writing parameters? The linked PR only implements writing.

**Comment by jessicaaustin** [comment]
Personally I think this should stay open until reading parameters is implemented. @jtbandes

**Comment by foxymiles** [comment]
@jessicaaustin Is the parameter access implemented in https://github.com/foxglove/studio/pull/2154 not working for you?

**Comment by foxymiles** [comment]
@jtbandes @jessicaaustin Sorry if this wasn't clear but read access to parameters was implemented in #2154 by adding parameters to the `RenderState`. I had to delay implementing write access to parameters until this separate PR because there was an underlying issue in our ROS1 implementation I had to fix. But you should be able to both read and write params via the extension panel API now.

**Comment by amacneil** [comment]
Summary: 
- Reading params was added in https://github.com/foxglove/studio/pull/2154
- Writing params was added in https://github.com/foxglove/studio/pull/2316

Both should be working in the latest release (v0.24.0). Please add comments or open a new issue if anything is not working.
