### ISSUE TITLE
Make panel directories, titles, and types consistent with each other

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#2156]
- Should include plan to migrate legacy layouts to use updated panel types

**Comment by defunctzombie** [comment]
@esthersweon Is there anything outstanding to do here? I think we've tackled any relevant items as we've iterated on the code.

**Comment by esthersweon** [comment]
@defunctzombie - I still see the Log panel with a `panelType` of `"RosOut"`, and the Image panel with a `panelType` and directory name of `ImageView`.

Likely that there are other inconsistencies.

Not an urgent issue, but feels like something we should do to make contributing easier for open source folks.

**Comment by defunctzombie** [comment]
@esthersweon We are not planning on changing the panelType since that would break existing layouts. We could create logic for backwards compat for hose but it seems of little value. Probably we can close this ticket out and if there are specific enhancements we need to do that come up in the context of bugs or features we can do them.
