### ISSUE TITLE
Hide "Add" button on "State Transitions" panel when pointer is not on the panel.

### ISSUE THREAD

**Issue by bunnyc1986** [foxglove/studio#2211]
Currently, the "add" button blocks part of the plot. Could you please make it hidden when mouse pointer is not on the panel like the common toolbar? 

![image](https://user-images.githubusercontent.com/1644274/143154549-6b63b4a7-1188-473f-ab08-b1cc1338c6fa.png)

**Comment by jhurliman** [comment]
![](https://user-images.githubusercontent.com/195374/146093900-fe533467-8010-403c-8dd5-dfa207c7950f.png)

**Comment by defunctzombie** [comment]
@2metres sending this bug your way. As a start we could match the plot panel behavior to hide the button unless hovered. I think in this case we might want to do better since when you hover this button covers important parts of the dataset.

Some ideas:

- Make state transition panel only support one dataset and the user opens multiple panels to show multiple datasets. Since we have timeseries pan/zoom sync this would still work.
- Add a button under the entire plot to add a series
- Whatever other magical idea you can think of for the add button

**Comment by foxymiles** [comment]
<img width="1725" alt="Screen Shot 2022-01-12 at 8 46 22 AM" src="https://user-images.githubusercontent.com/93935560/149173323-e8635b85-4f23-475d-8cac-6376be7bdb37.png">

How about making it an always visible button in the bottom right corner?

**Comment by defunctzombie** [comment]
If you have a short panel then it will overlap your dataset.

**Comment by foxymiles** [comment]
@defunctzombie Yeah I don't see anywhere we can put it where it will never overlap. Should I go ahead and hide it when not hovered? The "reset view" button has a similar issue.
