### ISSUE TITLE
Stepping through a bag results in a different end state than playing a bag

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2270]
[markertest009.bag.zip](https://github.com/foxglove/studio/files/7652913/markertest009.bag.zip)

End state after playing back the bag to the end:
<img width="930" alt="Screen Shot 2021-12-03 at 3 31 03 PM" src="https://user-images.githubusercontent.com/195374/144685851-ea25dc96-b9d5-4096-ab86-7e68e32bef68.png">

End state after pressing the right keyboard button until the end of the bag is reached:
<img width="930" alt="Screen Shot 2021-12-03 at 3 31 13 PM" src="https://user-images.githubusercontent.com/195374/144685861-e7004039-eafd-41b2-887d-1389e6293e14.png">

**Comment by jtbandes** [comment]
This is kind of by design. Stepping is really a seek, and seeking to the end can result in a different end state as well.

I think the ticket should specifically call out TFs or markers, because those are some of the only things the app displays in a truly stateful manner (where to display them correctly you technically need to process every preceding message in the entire bag)

**Comment by amacneil** [comment]
From live discussion: Let's scope this to supporting "step forward in time" only (e.g. for seeks <100ms).

Seeking forward large distances, or stepping backwards can continue to treat this as a seek and throw away existing visualization state.
