### ISSUE TITLE
Auto-select frame when adding first topic to 3d panel

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#2338]
1. Add a new 3d panel (no render frame is selected)
2. Select a topic

Current behavior: Nothing appears in the scene, because no frame is selected so we don't render anything
Desired behavior: When you select the first topic, if no frame is selected, we should auto-select the header frame for that topic, so that something actually appears on the screen.

**Comment by jhurliman** [comment]
@defunctzombie was this fixed as a side effect of your recent UrdfBuilder fix?

**Comment by defunctzombie** [comment]
Nope - but I think we do auto-select a frame when there are transforms available. Which may not correspond to the first topic you select.

The current behavior described above is no longer accurate. When you add a new 3d panel and open a data source, we _will_ select _some_ frame and display that always. We no longer collapse the follow frame text label.

We can still change the automatically selected frame when the user selects their first topic to the topic they selected. But we would only do this if the user did not previously select a follow frame since we consider that setting from the 3d panel to override any auto detection we try to perform.

I think with our new frame detection and UI around follow frames this issue could be less relevant for new user experience and we could close it out.

@amacneil give the app a go from a fresh setup and see if there is a more specific behavior you want.

**Comment by jhurliman** [comment]
Since we now auto-select a frame when the user has not selected a frame but there is one available, I think we can close this ticket as fixed. If we want more advanced frame auto-selection, or changing the currently selected frame on behalf of the user as new data comes in, it should probably be described in a new `ux` ticket.
