### ISSUE TITLE
"Data sources" sidebar, Duration should show nanoseconds when nanosecond-level timestamps are enabled

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#2481]
Studio allows toggling between "human-friendly" time and "whole_seconds.fractional_seconds" formatting. When the latter is selected, the "Duration" field of the Data sources sidebar should show full nanosecond precision instead of rounding to the nearest millisecond.

<img width="277" alt="Screen Shot 2021-12-22 at 11 07 14 AM" src="https://user-images.githubusercontent.com/195374/147142868-7b734139-5b2c-49ea-acb4-10a5df87f23b.png">

**Comment by jtbandes** [comment]
I personally don't think it particularly makes sense to tie the time format directly to the seconds' precision. They could be two separate settings or we could just always show nanosecond precision.

The screenshot you showed is also weird because it shows "date > time", but the time is an absolute time rather than being relative to the date...

**Comment by jtbandes** [comment]
Removing bug label – this issue doesn't really render the app broken.
