### ISSUE TITLE
Raw message panel resets what parts of the message is collapsed when bag loops

### ISSUE THREAD

**Issue by clementchef** [foxglove/studio#2688]
Small bug in the raw message panel. Let say I want to see all details: I have to click all the drop down manually (which is fine to do once). However as soon as you loop the bag you lose whatever subtree you were seeing. Everything become collapsed again. You have to reopen the message tree manually everytime. Could this be saved somehow? even saved in layout if people always care abou the same subtree?

- Version:  0.25.1
- OS: ubuntu 18.04

**Steps To Reproduce**
Open raw message panel, expend a message subfiled, loop over the bag.

**Expected Behavior**
Panel should not change.

**Actual Behavior**
Panel collapses all fields.

**Comment by defunctzombie** [comment]
@clementchef I'm working on a fix for this - just waiting on some updates to a library we use for the tree view.

As a workaround - I learned that clicking on the field name (rather than the arrow) to expand/collapse will remember the state when the bag loops. The bug comes from different handling of clicking the field name vs clicking arrow.
