### ISSUE TITLE
Add .obj mesh support to mesh markers and robot descriptions

### ISSUE THREAD

**Issue by horverno** [foxglove/studio#3088]
**Description**

Connected to local ROS, the 3D marker topics and the URDF does not load.

- Version: Foxglove v1.4.0 / v1.5.1 / v1.6.0 and `ROS melodic` / `ROS noetic`
- OS: `Ubuntu 18.04` / `Ubuntu 20.04` 

**Steps To Reproduce**

3d topic:
```
cd ~/catkin_ws/src
git clone https://github.com/szenergy/rviz_markers
catkin build rviz_markers
source ~/catkin_ws/devel/setup.bash 
roscore
roslaunch rviz_markers demo1.launch
```
urdf:

```
cd ~/catkin_ws/src
git clone https://github.com/szenergy/nissan_leaf_ros
catkin build nissan_bringup
source ~/catkin_ws/devel/setup.bash 
roscore
roslaunch nissan_bringup 3d_nissan.launch 
roslaunch nissan_bringup tf_nissanleaf_statictf.launch
roslaunch nissan_bringup rviz00.launch
```

**Expected Behavior**

Display 3D data similar to RVIZ.

**Actual Behavior**

![foxglove_01_a](https://user-images.githubusercontent.com/11504709/160600912-44412c00-75b0-49c7-aadf-0992069146d9.png)

![foxglove_02](https://user-images.githubusercontent.com/11504709/160601884-8e81c7d5-010b-41a4-bf0b-649b1b532326.png)

i also tried to `/robot_description` to `package://nissan_bringup/param/nissan_leaf_robotdescription.ref.xml`, it did not solve the issue.

![foxglove_try_02_bb](https://user-images.githubusercontent.com/11504709/160601047-711962cf-bba7-4d84-a199-073a54be1c67.png)

Thank you!

**Comment by jtbandes** [comment]
Hi, can you please share more details on the error messages from the developer console? (Press Alt key > View > Advanced)

It seems like the problem might be that the `nissan_bringup` package is not in your `ROS_PACKAGE_PATH` (that's why you get the "404" errors when trying to load the meshes). You can edit the `ROS_PACKAGE_PATH` by updating the environment variable before running Studio (e.g. launching Studio after `source ~/catkin_ws/devel/setup.bash`), or directly in the app settings (bottom button in the sidebar).

**Comment by horverno** [comment]
Hi @jtbandes 

Thanks for the quick reply, i tried your suggestion sadly it did not worked.

The errors are the following:

```
x-foxglove-ros-package:?targetPkg=nissan_bringup&relPath=param%2Fnissan_leaf_robotdescription.ref.xml:1          

Failed to load resource: net::ERR_<unknown>
```

```
TypeError: Failed to fetch: x-foxglove-ros-package:?targetPkg=rviz_markers&relPath=stl%2Flexus.stl
```

Can I use an absolute path instead of the relative one somehow? Maybe this could solve the issue.

**Comment by jtbandes** [comment]
Can you also try with Studio v1.5? Some changes to package loading were made which might affect this: https://github.com/foxglove/studio/pull/2970

**Comment by horverno** [comment]
I learned that the newest build available is 1.4.0 at the moment.

``` r
$ sudo apt install foxglove-studio
Reading package lists... Done
Building dependency tree       
Reading state information... Done
foxglove-studio is already the newest version (1.4.0).
```

In the meantime I also tested it on `Ubuntu 20.04` and `ROS noetic` and `Ubuntu 18.04` and `ROS melodic`, the same issue is present.

I have two options now: wait for `v1.5` or build from source which I did not found any instructions. Considering the speed of the releases it only will take a couple of days, so I decided to wait.

**Comment by horverno** [comment]
hi @jtbandes  I tried `v1.5.1` different error message, but same output

![MicrosoftTeams-image](https://user-images.githubusercontent.com/11504709/160999603-dc4c5034-9943-45d4-9081-7b7b9dcecf9d.png)

**Comment by defunctzombie** [comment]
@horverno Thanks for following up with this. To help us reproduce the issue - could you confirm what your ROS_PACKAGE_PATH setting is within the Studio desktop app? I see above that you clone the repos to `~/catkin_ws/src` and want to make sure I've understood correctly how that relates to the package path.

**Comment by horverno** [comment]
@defunctzombie thanks, i can confirm, that the ROS_PACKAGE_PATH in the Foxglove Studio desktop app contains among others the following: 
``` r
/home/he/catkin_ws/src/nissan_leaf_ros/nissan_bringup:/home/he/catkin_ws/src/rviz_markers:/opt/ros/melodic/share
```

![image](https://user-images.githubusercontent.com/11504709/161326313-48b538f6-c42e-4f09-b358-499d2b1a29b4.png)

**Comment by horverno** [comment]
@defunctzombie @jtbandes i tried `v1.6.0` but the issue is still there

I also ask the people who i know have experience with this: @rudolfkrecht @norbertmarko @umiklos @csaplaci where somebody able to load 3d models? If yes, how?

**Comment by defunctzombie** [comment]
@horverno the referenced fix is not in a release yet.

Also worth noting that your ROS_PACKAGE_PATH has `/home/he/catkin_ws/src/nissan_leaf_ros/nissan_bringup` which isn't correct. It should be `/home/he/catkin_ws/src` to point to the root where to find packages.

Until the fix is part of a release I think you could try `/home/he/catkin_ws/src/nissan_leaf_ros` as a path. With the fix, you will be able to specify the workspace root src and Studio will find packages recursively from there.

**Comment by horverno** [comment]
thanks @defunctzombie 

did I understand correctly that your suggestion was to directly give `/robot_description` the path like this: 

```
/home/he/catkin_ws/src/nissan_leaf_ros/nissan_bringup/param/nissan_leaf_robotdescription.ref.xml
```
instead of `package://` like this
```
package://nissan_bringup/param/nissan_leaf_robotdescription.ref.xml
```

![robot_desc](https://user-images.githubusercontent.com/11504709/162754861-5473b892-7705-48ab-9bd9-11a6e9ba3090.png)

I did this but did not solve my issues. Also I tried other URDF's such as [ANYbotics/anymal_c_simple_description](https://github.com/ANYbotics/anymal_c_simple_description) these won't work either.

**Comment by horverno** [comment]
@defunctzombie @jtbandes i tried `v1.7.0` the error message disappeared, but still no 3D model


``` csharp
[main/main.js] Foxglove Studio 1.7.0
[main/main.js] initializing Sentry in main
[main/main.js] Could not set app as handler for foxglove://
[main/main.js] Elapsed (ms) until new StudioWindow: 123
[main/main.js] New Foxglove Studio window 1
[main/main.js] Starting update loop
[main/main.js] load-pending-files
[main/main.js] injectFilesToOpen: no files - skipping
[main/main.js] window URL loaded
[main/main.js] Load: package://nissan_bringup/param/nissan_leaf_robotdescription.ref.xml
[main/main.js] ROS_PACKAGE_PATH /home/he/catkin_ws/src/nissan_leaf_ros
[main/main.js] searching /home/he/catkin_ws/src/nissan_leaf_ros for packages
[main/main.js] Resolved: /home/he/catkin_ws/src/nissan_leaf_ros/nissan_bringup/param/nissan_leaf_robotdescription.ref.xml
[main/main.js] Checking for updates
```

**Comment by defunctzombie** [comment]
@horverno Thanks for following up. I've looked into this and determined that the root cause is that we don't _yet_ support loading `.obj` meshes. We are actively working on many 3d panel enhancements that will allow us to better support meshes like `.obj` files.

I'm going to change this ticket from a bug to a feature and update the title to indicate that the 3d panel should support .obj meshes for URDF (robot descriptions) and mesh markers.

In the meantime, I've also made a ticket to improve the error feedback when we do encounter a mesh we don't yet support. This should not fail silently but should let you know what happened.

https://github.com/foxglove/studio/issues/3198

**Comment by horverno** [comment]
I can confirm that with `v1.8.0` the situation is better. Our URDF still  have some issues, but https://github.com/ANYbotics/anymal_b_simple_description seem to work. We will compare what's the difference and will improve accordance to that. Thanks
![anymal1](https://user-images.githubusercontent.com/11504709/164205986-1c9993b2-c906-4e77-b7b4-a3b644524948.png)
![anymal2](https://user-images.githubusercontent.com/11504709/164205994-4f4f848c-a49a-41df-9142-4fc7fea1a414.png)
.

**Comment by jhurliman** [comment]
The title of this ticket, ".obj mesh support", is completed in the new `3D (Beta)` panel. If there are additional rendering issues with the URDF support in the new 3d panel in 1.18 (due to release early next week) let's open a new ticket to scope down the work and classify it as a bug report or feature request.
