### ISSUE TITLE
Typing in node playground tab moves cursor to end

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#3147]
<img width="233" alt="image" src="https://user-images.githubusercontent.com/14237/161878065-5716525f-fa6b-425e-9eb7-9b56a30a9f2d.png">

When I type in this field to rename my node, the cursor jumps to the end after every keystroke, so editing what I've already typed is really hard.

**Comment by defunctzombie** [comment]
This is happening due to the onChange event for the input not causing the name to be applied immediately on the next render.

Below I have instrumented the onChange event with a console log showing the new value and also instrumented the render call to log the `inputTitle`. Immediately after changing the value in the input onChange, the component re-renders but does not have the correct value for inputTitle.

<img width="870" alt="image" src="https://user-images.githubusercontent.com/84792/164149090-488c19d6-afaa-4647-878f-fbb7b2e647da.png">

My learnings from https://github.com/facebook/react/issues/955 indicate that this causes the underlying `input` component to lose the cursor position.

I'm exploring where to apply a fix here but until I have that wanted to provide this update.
