### ISSUE TITLE
Some node names break node playground typechecking

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#3148]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/14237/161878160-28719182-4ee6-4ac7-9712-0de5f3728679.png">

<img width="496" alt="image" src="https://user-images.githubusercontent.com/14237/161878174-813b57c8-6ee0-4c0e-8810-bbbc5404e2d4.png">

When a node name does not start with `/studio_node`, typechecking is broken in the editor. The node still works at runtime though.

**Comment by defunctzombie** [comment]
This happens because the node name is also used as the "filepath" in the "virtual" project structure. Files like `types.ts` are hard-coded to have a file name like `/studio_node/types.ts`. When you change the node name, this becomes its new full path and `./types` is no longer resolved because it is no longer at the same "path".

**Comment by jtbandes** [comment]
Yes, I think we need to stop using the node name as part of the filepath. I'm not sure if there was any valid reason to do that but it seems unnecessary.
