### ISSUE TITLE
Track message counts and frequencies for live connections

### ISSUE THREAD

**Issue by AndrewNolte** [foxglove/studio#3172]
**Description**
Message count and frequency values show "---" when using foxglove websocket

![image](https://user-images.githubusercontent.com/24322714/162806836-b460c4cc-f5dc-4361-a88e-d490ccc2cc27.png)

- Version: Latest webapp
- OS: Ubuntu 20.04

**Steps To Reproduce**
Connect to a foxglove websocket connection
Open a Data Source Info Panel

**Expected Behavior**

**Actual Behavior**

**Comment by defunctzombie** [comment]
Also worth noting that these fields won't be available for topics which do not have active subscribers from other panels since studio does not subscribe to all topics.

Today this is by design for live connections.

Changing this over to a feature request for seeing message counts and frequencies for live connections.

**Comment by AndrewNolte** [comment]
Actually it makes sense that it shouldn't work for all topics on live connections. I just noticed that it also isn't working on data platform files either.
