### ISSUE TITLE
Error: new playerState was emitted before last playerState was rendered

### ISSUE THREAD

**Issue by foxymiles** [foxglove/studio#3375]
**Description**
This error occurs sometimes when changing layouts or data sources.

```
Uncaught (in promise) Error: New playerState was emitted before last playerState was rendered.
    at listener (index.tsx?2844:200:1)
    at UserNodePlayer.eval [as _listener] (OrderedStampPlayer.ts?96f9:97:1)
    at UserNodePlayer._emitState (index.ts?3d38:541:1)
    at UserNodePlayer._onPlayerState (index.ts?3d38:523:1)
    at async IterablePlayer.eval [as _listener] (index.ts?3d38:549:1)
    at async IterablePlayer._emitState (IterablePlayer.ts?0830:469:1)
```

- Version: 1.11
- OS: macOS

**Steps To Reproduce**
Rapidly switch among different layouts.

**Expected Behavior**
No error should arise.

**Actual Behavior**
This exception is thrown.

**Comment by foxymiles** [comment]
@jtbandes Is this condition severe enough we need to throw an error? Maybe logging it would be sufficient?

https://github.com/foxglove/studio/blob/bef9bdccb6d8d877dda0cda652ae30d8199880f4/packages/studio-base/src/components/MessagePipeline/index.tsx#L313-L315

**Comment by jtbandes** [comment]
This indicates a breakage of the Player API contract. I can't really predict what may go wrong if it is violated. Certainly a violation only when switching data sources / layouts is not as bad as a violation during regular playback, so there might not be much harm done right now, but it still seems preferable to fix rather than downgrade to a warning and potentially invite future harm...
