### ISSUE TITLE
Layout doesn't load until data source is loaded

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#3492]
When I have a layout & local file source loaded, and I reload the app, my layout in the background is blank until I select a new data source.

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/14237/171926742-e79909e6-2534-4b11-a588-2d858399ef12.png">

If I exit out of the open dialog instead of selecting a source, no layout is selected, even though I had one selected before reloading:

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/14237/171926852-661c31ca-4dc7-4310-9b2a-3350154a2792.png">

**Comment by foxymiles** [comment]
This is a side effect of waiting until a datasource is selected before loading layouts in the hopes that that will prime the app to do a layout sync after the ds is loaded.

At some point we're going to have to stop putting bandaids on this architecture and take a step back and make session startup a single unified process instead of an unrelated bunch of async actions on multiple different contexts.
