### ISSUE TITLE
Bulk save, revert, export, and delete layouts

### ISSUE THREAD

**Issue by jackiescanlon** [foxglove/studio#3615]
It would be awesome if we could bulk save, revert, export and delete layouts. Right now, the user must click the dot or three dots next to each layout and perform the action one at a time.

![image](https://user-images.githubusercontent.com/43035541/173833924-2a4bbc14-4546-4a55-b09e-e14606d29aa1.png)

**Comment by amacneil** [comment]
+1

Especially bulk delete would be super helpful

**Comment by jtbandes** [comment]
cc @2metres – we would need some designs around how the selection should work. Or better, refactor this whole thing to use some Mui off the shelf component?

**Comment by foxymiles** [comment]
@jackiescanlon All of these are implemented now except for bulk export which is a bit more complex. How important is bulk export to your workflow?

**Comment by jackiescanlon** [comment]
Thanks so much! It would be useful at some point but having the other bulk actions is already a huge improvement.

**Comment by amacneil** [comment]
Thanks for the feedback!

Closing this ticket since the most important bulk actions have been implemented.

Bulk export would require us to zip the exported layouts client side (since browsers can't reliably trigger multiple downloads at once), and I'm not sure that is worth the additional technical complexity, especially since exporting layouts is really only used for debugging.
