### ISSUE TITLE
Hide all topics by default (matches behavior of old3d)

### ISSUE THREAD

**Issue by jhurliman** [foxglove/studio#3692]
For now let's focus on feature parity rather than changing the default topic behavior of the 3d panel. It is not obvious that we should be turning on all topics by default.

**Comment by defunctzombie** [comment]
@jhurliman can you please make this change this week - it's an easy change and been sitting on the backlog.

**Comment by defunctzombie** [comment]
Re-opening this issue because I am still seeing transforms on the screen when I open a new 3d (Beta) panel.

Here's a comparison of the current 3d panel and 3d (beta). I've opened the nuscenes sample dataset and added both panels to a new empty layout.

![image](https://user-images.githubusercontent.com/84792/179270823-e8c3c57b-4da2-4fa5-b7b8-03b4e096e330.png)

**Comment by defunctzombie** [comment]
Spoke in slack. We agreed to leave these visible for now since 3d (beta) unconditionally subscribes to transform messages so there's no additional "cost" in showing these by default.

We also mentioned that having a grid in the scene by default would be a nice visual to orient the display and make it obvious its not broken if there's nothing else to render.
