### ISSUE TITLE
3D beta frame error is stuck

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/studio#3863]
I was looking at a data source with a base_link frame. I then opened a different data source that did not have a base_link and turned on a topic to show. The 3d panel automatically changed my frame to the topic's frame and is showing an error.

<img width="398" alt="Screen Shot 2022-07-18 at 9 21 45 AM" src="https://user-images.githubusercontent.com/84792/179566198-2e4aa915-598c-4782-86bc-bb38559eab9c.png">

I've tried re-selecing the new frame in the drop down but the error persists.

**Desired Behavior**

It is un-intuitive to have to "re-select" a frame manually if I see it is already selected. I'd rather have seen a topic error telling me that there is no transform from `base_link -> vertical` and realized I need to change my frame than have whatever auto-magic switch the frame for me when I toggle topics.

**Comment by jhurliman** [comment]
> I'd rather have seen a topic error telling me that there is no transform from base_link -> vertical

This is not the problem that is encountered, the problem is you manually selected a frame named `base_link` at some point and then you loaded a data source that does not have a frame with that name. At that point we pretty much have two options:

1. Show a blank 3D panel, set the Frame dropdown to no selection (blank), and show a sidebar error saying `Frame "base_link" not found`
2. Use our default auto-frame selection logic to choose a frame in the current data source, but warn the user with a sidebar error that the frame they manually selected is not available and another frame is being used for rendering instead (the current behavior).

Which option should we go with?

**Comment by amacneil** [comment]
What about a variation on (1): Show a blank 3D panel, set the Frame dropdown value to `base_link`, show a sidebar error saying `Frame "base_link" not found`.

That way it's clear that the currently selected frame doesn't exist. I can hit the dropdown and choose a different frame (to be clear, assuming MUI allows this, I would expect the field to show `base_link`, but `base_link` would not be in the list of dropdown options when I go to select a new frame).

**Comment by jhurliman** [comment]
@amacneil that's not allowed with the settings sidebar API (I assume due to MUI internals) today. You get a console warning and a blank selection. The closest we can do is add "base_link" to the dropdown, but selecting it continues to show the sidebar error. And as soon as you select a different frame, "base_link" would disappear from the options. It's a bit weird (IMO) UX-wise but doable.

**Comment by amacneil** [comment]
Can we confirm if that's a mui limitation or just something we enforced? 

"Dropdown that provides options but can also accept arbitrary text" is a common UI widget. I think using that here would make the most sense, since there may be genuine needs for users to have it set to a frame that has not yet been published.

**Comment by amacneil** [comment]
Like this: https://27r9hk.csb.app/

**Comment by jhurliman** [comment]
@amacneil that's a different type of control that allows you to type arbitrary text.

**Comment by amacneil** [comment]
That control seems like a good fit for this problem though right? It allows find as you type, but it doesn't allow selecting arbitrary text.
