### ISSUE TITLE
3D Beta panel doesn't display first frame

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3886]
**Description**
When loading the sample data set with an existing layout, the 3D panel is blank until playback starts. Other panels (e.g. Image panel) always show me the first frame when I load a data source.

Edit: Seems to work fine with experimental bag player. 

https://user-images.githubusercontent.com/637671/180083303-f75ce37d-9775-4313-9dee-7399d803666d.mov

- Version: main
- OS: web
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): sample data

**Comment by jhurliman** [comment]
This is not a default 3D panel layout. Note that your top-level `Transforms` setting node has been hidden. The expected behavior of a fresh new3d panel is to see the TF hierarchy visualized and nothing else (screenshot attached).

Markers only appear after a bit of playback because not all transforms are available upon initial load. This is due to the look-forward window not being far enough to see all the relevant transforms.

**Comment by amacneil** [comment]
Yes it is not supposed to be a fresh 3d panel. However, with an existing layout I should be able to load a data source and see the first frame.

However, I'm ok with closing this because we realized during debugging that it works fine in the experimental player, which will be enabled by default very soon.
