### ISSUE TITLE
3D Beta: Merge General/Scene/Camera under Scene

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3888]
**Description**

Clean up the 3D Beta sidebar:

- [ ] Move `Frame` setting (now `General`) under `Scene`
- [ ] Rename `Camera` to `View` and nest under Scene
- [ ] Rename `Color` to `Background`

<img width="385" alt="image" src="https://user-images.githubusercontent.com/637671/180086372-8b812fd5-2ba4-49e6-ba83-d497160f8e05.png">

**Comment by amacneil** [comment]
@jhurliman what do you think about moving `Frame` under `Scene`?

**Comment by jhurliman** [comment]
@amacneil I started the PR with that and @defunctzombie suggested changing it. I agreed; it was an overall degradation of the UX because it put an important field (the Render Frame) in line with other fields that are less important and shouldn't be changed often, and it required the full Scene node to be expanded which pushed more transform and topics content below the fold.

**Comment by amacneil** [comment]
Ok - makes sense
