### ISSUE TITLE
Db3: Data source topic list should show all topics, including  unsupported ones

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#3967]
**Description**
I downloaded an open source db3 file from [here](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/).

When I open it in Foxglove Studio, the "Topics" list is missing a few topics:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/637671/181411919-d09c9fb1-f0d4-45e4-b033-86dff6620fdc.png">

They do show up in the "Problems" tab:

<img width="522" alt="image" src="https://user-images.githubusercontent.com/637671/181412216-10ff5a8c-fca9-453f-88e1-99385d7b13f8.png">

I think we should show all topics in the Topics list, even if we are missing a message definition. We could still list the topic name, schema name, and publish frequency. We could also show an error inline next to the topic (similar to sidebar settings errors).

**Comment by amacneil** [comment]
cc @defunctzombie for feedback

**Comment by defunctzombie** [comment]
I think it's up to the data source to emit the topics it wants to make available. In this case the db3 source I probably not adding these topics to its list since it doesn't have definitions for them.

Its a simple change to switch up the logic here: https://github.com/foxglove/studio/blob/main/packages/studio-base/src/players/IterablePlayer/rosdb3/RosDb3IterableSource.worker.ts#L74-L80

I don't have super strong feelings either way but seems fine to show the user the topic and datatype and change the warnings to something more actionable.
