### ISSUE TITLE
Sometimes some topics get "stuck" while others keep playing

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#4091]
**Description**

- Version: main
- OS: web
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): sample nuscenes

Sometimes during playback, my map and markers freeze up, but the lidar keeps playing. Happens on both old3d + new3d. Maybe it is related to transform frame locking?

https://user-images.githubusercontent.com/637671/183826194-7562a6fe-ecd9-4636-92c7-c00c8a5d731f.mov

**Comment by amacneil** [comment]
Here is a better video with some raw message panels shown:

https://user-images.githubusercontent.com/637671/183827313-0e57ff3c-541f-48cd-914f-f34c2ac74a9e.mov

There doesn't seem to be any obvious reason why this starts happening, but it does "fix" itself when the new tf message arrives.

Note this was on https://github.com/foxglove/studio/pull/4087 branch.

**Comment by defunctzombie** [comment]
I can confirm I am also seeing a behavior here that looks like missing messages. What I am seeing is that during playback, I can seek forward up-to and past a time when I know there is a _/tf_ message yet I won't see this message in the raw message panel.

There should be messages at:

* 1532402929.697797000
* 1532402930.152601000
* 1532402930.648325000

But I can definitely play forward in a way that causes one of these to be "skipped" which makes the scene look "stuck" because the /tfs are old. The annotations are in _map_ frame but there's no update of _map_ to _base-link_ so the annotations follow along with base link when instead they should appear further behind.

**Comment by amacneil** [comment]
This is still happening for me on latest main.

**Comment by defunctzombie** [comment]
@amacneil I am unable to reproduce this issue on studio.foxglove.dev. What topics are getting "stuck" for you? The behavior in the original video is no longer happening for me.

**Comment by amacneil** [comment]
Sample nuscenes, fresh layout with only 3D beta panel, all topics enabled.

Always, the lidar topic keeps moving, and every other topic gets stuck:

https://user-images.githubusercontent.com/637671/185271017-9a75629d-d4d8-4990-90dd-c89cbbe600dc.mov

Lmk how I can help debug.

**Comment by defunctzombie** [comment]
Looking closer at the video - what I see is that the car has stopped moving forward relative to the map. The lidar looks like it is still "moving" but what I see is that the lidar is getting updated with new messages and the points of the lidar are moving. The lidar itself is stationary relative to the car and other scene entities. I suspect that the marker messages are also still updating but are too stationary. These items would be stationary if the `map -> base_link` transform is not present or updating. That would result in the car no longer moving "forward" in the scene and all the markers and sensor readings looking "stuck" because their frames are all relative to base_link.

**Comment by defunctzombie** [comment]
@amacneil if you can make a recording of the above video with a raw message panel alongside the 3d panel. Subscribe to the `/tf.transforms[:]{header.frame_id=="map"}` in the raw message panel and lets see if that produces anything more to help debug.

**Comment by amacneil** [comment]
https://user-images.githubusercontent.com/637671/185301021-86b7685d-d3ba-4ede-8f80-d3ac042e5b35.mov

https://user-images.githubusercontent.com/637671/185301057-577388a1-fe0b-4e6c-b74f-57522fb88de8.mov

https://user-images.githubusercontent.com/637671/185301242-252703d2-f971-433c-9608-e2bc4d164c53.mov

**Comment by amacneil** [comment]
https://user-images.githubusercontent.com/637671/185718451-3f5da59e-16a2-4dc4-8c1a-ff18374cb5da.mov

**Comment by jtbandes** [comment]
Latest discovery from the above debugging session is that PanelExtensionAdapter overwrites its `latestPipelineContextRef.current` and can drop frames if the requestAnimationFrame does not happen by the time the previous pipeline context is processed. This could be remedied by adding correct usage of `pauseFrame` to the PanelExtensionAdapter.
