### ISSUE TITLE
Set theme color for better styling of web application

### ISSUE THREAD

**Issue by rgov** [foxglove/studio#4152]
`<meta name="theme-color" content="#27272b">` will signal to some browsers that it should make the browser chrome around the page match the color of the page.

You'd probably want to have this dynamically set by the in-app theme selection, though since that might take a second to load, perhaps it should have a default color selected with the `media` attribute?

https://stuffandnonsense.co.uk/blog/time-to-update-your-theme-color-meta-tag-for-safari

Here's how it gets autodetected on Safari with compact tabs:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/108767/184999812-b32d105c-cffc-4ba8-9087-be30d1ae6d23.png">

Here's how it could look with the sidebar color set:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/108767/184999904-2be25213-e098-484b-9e5d-6f061e05578f.png">

**Comment by jtbandes** [comment]
The plain `media="..."` approach won't work for us because the user is able to override the system setting by manually selecting light or dark mode in settings.

However, it sounds like it's possible to dynamically change the theme-color: https://blog.terrible.dev/Dynamically-changing-the-site-theme-meta-tag/
