### ISSUE TITLE
3D Panel can cause page freeze

### ISSUE THREAD

**Issue by KisonHe** [foxglove/studio#4618]
**Description**
When I connect foxglove studio to my robot the page instantly freeze. So I record a bag file and it still doesn't work. However my rviz is working normally (https://github.com/KisonHe/bug-report-bag-files Got a screenshot)

So I made a ROS bag file and used https://studio.foxglove.dev/ to open it, still it freezes. I am not good at js stuff but I think the 3D panel should not cause browser freeze in any case. I tried opening on many devices including iPad/Chrome, windows/edge,chrome they all freeze. The bag file is here https://github.com/KisonHe/bug-report-bag-files 

After some try i think it might be caused by the tf topic, not sure though

- Version:
- OS: Many OS tried. Manjaro linux, ubuntu ,windows, iPadOS 's browers. All freeze
- Data source bag file at https://github.com/KisonHe/bug-report-bag-files 
- ROS distro (if applicable): melodic

**Steps To Reproduce**

Download the bag file from https://github.com/KisonHe/bug-report-bag-files and open it with foxglove studio.(With a 3d panel)

**Expected Behavior**
It should not freeze

**Actual Behavior**
It freeze

Thx, have a good day :)

**Comment by defunctzombie** [comment]
Thank you for the bug report and bag file to reproduce. I can confirm I am able to reproduce with the latest version of studio web. We'll take a look and get this fixed.

**Comment by snosenzo** [comment]
Hey so, It looks like the tfMessages in your bag  (see image). 
<img width="374" alt="image (2)" src="https://user-images.githubusercontent.com/10187776/195395424-15f04a58-85e6-43c2-9d69-e935837e6684.png">
they aren’t formatted in the bag as we expect them to be.

the rotation and translation are on the baseTf message instead of being under tfMessage.transforms[0].transform.translation/rotation as our types specify:
```

export type Transform = {
  translation: Vector3;
  rotation: Quaternion;
};

export type TransformStamped = {
  header: Header;
  child_frame_id: string;
  transform: Transform;
};

export type TFMessage = { transforms: TransformStamped[] };

```
and what we have is congruent with https://docs.ros.org/en/noetic/api/tf2_msgs/html/msg/TFMessage.html
So I'm going to work on fixing the crash so that the panel doesn't freeze, but in the meantime if you change your bag to follow this format it should work. 
Also can we ask where this tfMessage comes from? if there's enough demand we could support it, we just haven't seen this before

**Comment by snosenzo** [comment]
So it turns out from further investigation that the root cause of the freeze is actually a cyclical transform tree created from the tfMessages. It looks like there's a cycle between the `base_link`, `odom` and `map` coordinate frames in the bag file.

**Comment by KisonHe** [comment]
> So it turns out from further investigation that the root cause of the freeze is actually a cyclical transform tree created from the tfMessages. It looks like there's a cycle between the `base_link`, `odom` and `map` coordinate frames in the bag file.

Thanks for your investigation :) Will check about tfMessages and try with fixed ones to see if it still freezes :)
