### ISSUE TITLE
[ERROR]: Exception calling subscribe callback: 'NavSatFix' object has no attribute '_buff'

### ISSUE THREAD

**Issue by woudie-swap** [foxglove/studio#4660]
**Description**
Hi All,

I was doing some testing with foxglove over a rosbridge websocket and started to encounter error on some topics regarding an attribute `_buff`. I have seen it now on a number of topics I tried using, but most recently encountered the issue while trying to using a map and subscribe to a NavSatFix topic. Any ideas on what is causing this issue?

- Version: 1.26.0
- OS: Ubuntu 20.04
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): rosbridge
- ROS distro (if applicable): melodic

**Steps To Reproduce**

1. publish a NavSatFix message to a topic
2. open rosbridge and websocket
3. try to subscribe and display from said navsatfix topic

**Expected Behavior**
Display marker on map and not output an error over rosbridge

**Actual Behavior**
generates the following error:
```
2022-10-18 04:03:30+0000 [-] [ERROR] [1666065810.215472]: Exception calling subscribe callback: 'NavSatFix' object has no attribute '_buff'
2022-10-18 04:03:30+0000 [-] [ERROR] [1666065810.306972]: Exception calling subscribe callback: 'NavSatFix' object has no attribute '_buff'
2022-10-18 04:03:30+0000 [-] [ERROR] [1666065810.404056]: Exception calling subscribe callback: 'NavSatFix' object has no attribute '_buff'
```

**Comment by defunctzombie** [comment]
This looks identical to: https://github.com/foxglove/studio/issues/3942 and has an old bug on rosbridge repo also mentioning the `_buff` variable: https://github.com/RobotWebTools/rosbridge_suite/issues/547

I recommend opening an issue on the rosbridge repo: https://github.com/RobotWebTools/rosbridge_suite but seeing that you are using `melodic` there might not be much hope for new packages since that distro isn't supported anymore.

From the rosbridge issue it looks like you might be subscribing from Studio as well as some other client and that is causing a conflict. Closing out this issue since this is on the rosbridge side. Feel free to reference this issue tho when you open a rosbridge issue.
