### ISSUE TITLE
Remote bag file fetch costs more than it's real size, and with some layout ，progress bar loads very slow

### ISSUE THREAD

**Issue by jetinnn** [foxglove/studio#4830]
**Description**
In Chrome network, for example, a 2GB remote bag file may costs 5GB data requests, much more than it's real size. And I found the progress bar loads very slow sometimes. Our network is ok, I don't know what causes this, maybe high frequency topics, or a layout panel that consume a lot of resources?

- Version: 1.31.0
- OS: Mac / Ubuntu
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): a remote bag file
- ROS distro (if applicable):

**Steps To Reproduce**

**Expected Behavior**

**Actual Behavior**

**Comment by defunctzombie** [comment]
This is by design. We currently have two code-paths for fetching topics to preload (for plot panels) vs buffering topics for regular playback. We've taken this approach to simplify some of our code paths. Because of these approaches we end up fetching parts of a bag file twice; once for the preloading topics and another time for topics during playback.

**Comment by amacneil** [comment]
It's also worth pointing out that a browser tab can only use ~2GB of memory. If you have a 5GB bag file, we are going to have to download it several times over as you visualize it (especially for example with Plot panel which must scan the entire remote file). We have another issue (https://github.com/foxglove/studio/issues/4220) discussing this same problem, but it's really an inherent issue with loading large files into the browser.

I recommend you test our [Data Platform](https://foxglove.dev/data-platform), which makes remote file streaming much more efficient because we can control how we store those files in the backend, and fetch individual topics without downloading the whole file.

**Comment by jetinnn** [comment]
But a small bag (200MB) also loads slowly when I add a log panel with a frequent topic. Without this panel, it loads very smoothly.
 The first video is a small bag loads without a frequent topic. The second one is the same bag with a frequent topic.

https://user-images.githubusercontent.com/30258205/202479686-58a227f7-82c5-4afd-acce-9c64f74c921b.mp4


https://user-images.githubusercontent.com/30258205/202480499-caa5d7ba-e32f-4e27-80d1-024154f96efa.mp4

**Comment by defunctzombie** [comment]
It's hard to say exactly without seeing how the data is structured in the file. If you can share the bag file with us (privately via email) we can take a look at reproducing the issue and seeing if there is an appropriate fix to apply. Without the file it is hard to guess at what might be happening.

**Comment by jetinnn** [comment]
ok, what's your email address?

**Comment by lizhucheng** [comment]
> This is by design. We currently have two code-paths for fetching topics to preload (for plot panels) vs buffering topics for regular playback. We've taken this approach to simplify some of our code paths. Because of these approaches we end up fetching parts of a bag file twice; once for the preloading topics and another time for topics during playback.

Fetching requests terminate  and resend too often because the blockloader and BufferedIterableSource in iterablePlayer fetch different ranges, and it pulls down brower seriously. 
![image](https://user-images.githubusercontent.com/10193114/210966421-c081e955-2a18-4d62-b671-bf2522bdd9a8.png)

**Comment by lizhucheng** [comment]
the option "enablePreload: true" has not been test in IterablePlayer.test.ts.
