### ISSUE TITLE
images in 3d only show the first frame and don't update

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#5725]
`_recomputeCameraModel` returns undefined if the camera model did not change between the current frame and previous, but undefined `cameraModel` return value causes the call to `this._updateImageRenderable(renderable, image, cameraModel, receiveTime, settings);` in `handleImage()` to be skipped so the new image data is discarded

[Slack Message](https://foxglove.slack.com/archives/C028UEY858S/p1680814696349569)

**Comment by jhurliman** [comment]
This should be the fix (in handleImage):

`const cameraModel = this._recomputeCameraModel(renderable, cameraInfo) ?? renderable.userData.cameraModel;`

**Comment by jhurliman** [comment]
It's desirable for _recomputeCameraModel to return undefined if nothing changed so the handleCameraInfo callback can be a mostly no-op if the camera model didn't change between messages, and it's uncommon for the camera model to change in real-time. That's why I think fixing it in this one place is better than changing _recomputeCameraModel

**Comment by defunctzombie** [comment]
> It's desirable for _recomputeCameraModel to return undefined if nothing changed so the handleCameraInfo callback can be a mostly no-op if the camera model didn't change between messages

👍 Thanks for that extra context. I see that the function has that comment that it returns undefined but now I understand why that is the case and how it impacts the logic.
