### ISSUE TITLE
3D crashed

### ISSUE THREAD

**Issue by 263868161** [foxglove/studio#5818]
**Description**
When I use 3D, a crash occurs.Works fine on older versions（1.2.0）.
![0424-1](https://user-images.githubusercontent.com/20036253/234151827-be7664d4-aaa9-4711-a7c4-b8dc20f2364c.png)
![0424-3](https://user-images.githubusercontent.com/20036253/234151874-1eb6fdb8-6699-4b90-9096-9c0e4f335cec.png)

- Version:1.51.0
- Platform:ubuntu 20.04
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):

**Steps To Reproduce**

**Expected Behavior**

**Comment by jtbandes** [comment]
Please upload the `/home/hy/temp/0424/parking_test/log/ora1_0423/0423_ora1_1.zip` file for testing.

**Comment by 263868161** [comment]
[0423_ora1_1.zip](https://github.com/foxglove/studio/files/11315670/0423_ora1_1.zip)

**Comment by jtbandes** [comment]
When I load this dataset, the 3D panel doesn't crash, but none of the topics are visualizable because there aren't any [types supported by the 3D panel](https://foxglove.dev/docs/studio/panels/3d#supported-messages). Is there more information about your setup that is missing from the bug report?

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/14237/234152881-b2e93ecf-11f7-4d7c-9b07-28b8e507d5b0.png">
<img width="495" alt="image" src="https://user-images.githubusercontent.com/14237/234152908-0ab7b875-d706-43df-b5d0-67da6ecb3a6d.png">

**Comment by jtbandes** [comment]
I'm going to close this issue since we haven't heard back, but feel free to post below if you have more debugging information to share.
