### ISSUE TITLE
3D crashed

### ISSUE THREAD

**Issue by 263868161** [foxglove/studio#5935]
**Description**

When I use 3D, a crash occurs.Works fine on older versions（1.2.0）.
![image](https://user-images.githubusercontent.com/20036253/236619911-c00f2672-01bf-4ad4-95f7-d8b15d0b89e8.png)
![image](https://user-images.githubusercontent.com/20036253/236619925-9efac4ab-e24e-4567-9efc-297122d3393e.png)
![foxglove_error](https://user-images.githubusercontent.com/20036253/236620857-6f429fde-9528-4f64-b632-8e7a83462d59.gif)

- Version:1.53.0
- Platform:ubuntu20.04
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):

**Steps To Reproduce**

**Expected Behavior**
[demo.zip](https://github.com/foxglove/studio/files/11412196/demo.zip)

**Comment by defunctzombie** [comment]
@263868161 What type of computer are you running this on? What are the graphics drivers you are using? To me this looks like a limitation with whatever graphics drivers you are using on your specific computer.

**Comment by 263868161** [comment]
My GPU is nvidia  GEFORCE GTX 1060, gpaphics drivers is "nvidia-driver-525"

**Comment by 263868161** [comment]
@defunctzombie Hi,I have uploaded the demo program, can't it run?

**Comment by jtbandes** [comment]
Hi again – we've made some performance improvements in #6034 that should help with your use case. I'm going to close out this issue for now since we haven't heard back recently, but feel free to report back or create a new issue if you are still having problems. (A sample bag/mcap file will be much easier for us to diagnose with than a sample program.)
