### ISSUE TITLE
Ability to publish pose to topic by clicking point in 3D panel

### ISSUE THREAD

**Issue by iceuw** [foxglove/studio#605]
Is there any way to publish the pose msg by click the point in 3D panel, just like the "2D Pose Estimate" button in rviz

**Comment by jtbandes** [comment]
Not currently, but thanks for the suggestion! We can leave this issue open to track it.

**Comment by jtbandes** [comment]
Another similar request (specifically for nav goals): https://github.com/cruise-automation/webviz/issues/664

**Comment by amacneil** [comment]
Hi! So that we can prioritize this, it would be helpful if people could chime in with which of the following rviz features would be most helpful:

- 2D Pose Estimate (publishes `geometry_msgs/PoseWithCovarianceStamped` on `/initialpose`)
- 2D Nav Goal (publishes `geometry_msgs/PoseStamped` on `/move_base_simple/goal`)
- Publish Point (publishes `geometry_msgs/PointStamped` on `/clicked_point`)

Also: do you want to customize the topics that these messages are published on, or are you happy with the rviz defaults?

**Comment by rowandempster** [comment]
@amacneil Thanks for taking this up 

For my immediate use case, 2D Nav Goal (publishes geometry_msgs/PoseStamped on /move_base_simple/goal) will suffice. Publish point functionality is also useful for sensor calibrations, and I would say is 2nd highest priority. These features can be released incrementally, i.e. my group would immediately benefit from 2D Nav Goal setting without the Publish Point functionality

**Comment by dthakur** [comment]
2D Pose Estimate (publishes `geometry_msgs/PoseWithCovarianceStamped` on `/initialpose`) is most important for us. No changes needed from the current `rviz` behavior. Just need x, y and yaw published. This helps us with relocalization.

**Comment by ccpowers** [comment]
@amacneil For our use case, we use both 2d nav goal (`geometry_msgs/PoseStamped` on a topic we call `/request/goal`) and 2d pose estimate (`geometry_msgs/PoseWithCovarianceStamped` on `/request/initial_pose`). We use them in simulation/development mostly, so it's easy enough to put a shim in to change topics if needed, especially since ours are not the standard topic names (but would be extra nice if we didn't have to). 

In the longer term, we have some other extensions that use interactive markers doing things like adding simulated objects and people to the environment which would be nice to port to foxglove.

**Comment by amacneil** [comment]
Thanks everyone! This is helpful. We will take a look at it in the coming weeks.

**Comment by schmittlema** [comment]
I would love all 3 with the default topics but priority would be.
1. 2D pose estimate
2. 2D nav goal
3. 2D point

**Comment by jtbandes** [comment]
Today we learned rviz has a Tool Properties panel where you can set the covariance that's used in the 2D Pose Estimate. ![image](https://user-images.githubusercontent.com/14237/149590593-5ab3396b-1342-42e6-ac94-920c8f245652.png)

**Comment by jtbandes** [comment]
RViz's pose/goal publishing shows an arrow and fixes the length of the arrow, rather than allowing 2 arbitrarily located points:

https://user-images.githubusercontent.com/14237/151252579-5a8b6057-4dc9-48f1-8eac-6cdc62e39d7a.mov

**Comment by foxymiles** [comment]
Enhancements:

1. Use arrow of fixed length for pose drawing.
2. Add link to settings from the popout menu.
3. Use message type in popout menu instead of `goal`, `pose`, `point`
4. Improve icons?

**Comment by foxymiles** [comment]
> RViz's pose/goal publishing shows an arrow and fixes the length of the arrow, rather than allowing 2 arbitrarily located points:
> 
>  Screen.Recording.2022-01-26.at.1.46.50.PM.mov

Thanks for the reference. I've updated it to work more like this now.
