### ISSUE TITLE
"Cannot identify bag format" error

### ISSUE THREAD

**Issue by amacneil** [foxglove/studio#682]
To reproduce this, try to load a bag that is not a valid rosbag file. The RandomAccessPlayer has a generic catch for any player errors that calls `this._setError("Error initializing player", error, "app");` which reports this user error (opening a bad file) as an application error to Sentry. We need to surface this as a user error somehow.

via @jhurliman

**Comment by defunctzombie** [comment]
This issue was fixed when I re-worked how player errors are reported. I tested now with two bag files. The first is a text file with a .bag extension (so no ROSBAG header).

<img width="165" alt="Screen Shot 2021-05-15 at 6 01 34 PM" src="https://user-images.githubusercontent.com/84792/118382222-fd5f9e00-b5a7-11eb-9970-c10b27edf404.png">
<img width="630" alt="Screen Shot 2021-05-15 at 6 01 39 PM" src="https://user-images.githubusercontent.com/84792/118382223-018bbb80-b5a8-11eb-9c09-33c9fcb5eab2.png">

The second is a file with a valid rosbag header but invalid content after the header.

<img width="610" alt="Screen Shot 2021-05-15 at 6 03 04 PM" src="https://user-images.githubusercontent.com/84792/118382229-110b0480-b5a8-11eb-891f-2e9cdf8ac0e0.png">

Both resulted in a warning icon next to the source name in the toolbar to let the user know the file is invalid.
