### ISSUE TITLE
`WebGL2 not supported` panels in Raspebrry Pi 5 (Ubuntu 23.10) 

### ISSUE THREAD

**Issue by iftahnaf** [foxglove/studio#7277]
**Description**

- Version: 1.82.0
- Platform: Raspberry Pi 5 - Ubuntu 23.10
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): rosbeidge

**Steps To Reproduce**
When choosing Image or 3D panel, there is an error and the panel is blank with `WebGL2 not supported` message.

**Expected Behavior**
Regular panel that shows image or PC.

**Comment by jtbandes** [comment]
WebGL 2 is required for these app features. I would recommend that you try visiting https://get.webgl.org/webgl2/ & https://webglreport.com/?v=2  and search the internet for advice on getting WebGL 2 to work on a Raspberry Pi 5, since you will probably find more people knowledgeable on that specific configuration elsewhere.
